version: '3'

networks: 
    laravel:
        driver: bridge

services: 
    nginx:
        image: nginx:alpine
        container_name: dnews_nginx
        restart: unless-stopped
        tty: true
        ports:
            - "8000:8000"
        volumes: 
            - ./src:/var/www/app
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        depends_on: 
            - php
            - mysql
        networks: 
            - laravel

    mysql:
        platform: linux/amd64
        image: mysql
        container_name: dnews_mysql
        restart: unless-stopped
        tty: true
        ports: 
            - "3306:3306"
        volumes: 
            - ./mysql:/var/lib/mysql
        environment: 
            MYSQL_DATABASE: news
            MYSQL_USER: admin
            MYSQL_PASSWORD: 123456
            MYSQL_ROOT_PASSWORD: root
            SERVICE_TAGS: dev
            SERVICE_NAME: mysql
        networks: 
            - laravel

    php:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: dnews_php
        restart: unless-stopped
        tty: true
        working_dir: /var/www/app
        volumes: 
            - ./src:/var/www/app
        ports: 
            - "9000:9000"
        networks: 
            - laravel
